product As screen:

    "'Header Label_1' As label":
        Align: =Align.Center
        Color: |
            =Color.White
        Fill: =Color.Black
        Height: =60
        Size: =18
        Text: ="Invoice Management"
        Width: =1366
        ZIndex: =1

    "'User Label_1' As label":
        Align: =Align.Right
        Color: =Color.DarkGray
        Text: ="Hello, " & User().FullName
        Width: =200
        X: =1166
        ZIndex: =2

    "'Logo Image_1' As image":
        Height: =60
        Image: =téléchargement
        Width: =200
        ZIndex: =3

    Icon1_1 As icon.BackArrow:
        Color: =Color.DarkGray
        Height: =60
        Icon: =Icon.BackArrow
        OnSelect: =Back()
        Width: =60
        X: =220
        ZIndex: =4

    Form1 As form:
        DataSource: =product_1
        DefaultMode: =FormMode.New
        X: =18
        Y: =110
        ZIndex: =5

        Titre_DataCard1 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="Title"
            Default: =ThisItem.Titre
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@product_1],DataSourceInfo.DisplayName,"Title")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@product_1], DataSourceInfo.MaxLength, "Title")
            Required: =true
            Update: =DataCardValue1.Text
            Width: =266
            X: =0
            Y: =0
            ZIndex: =6

            DataCardKey1 As label:
                AutoHeight: =true
                Height: =34
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue1 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey1.Y + DataCardKey1.Height + 5
                ZIndex: =2

            ErrorMessage1 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue1.Y + DataCardValue1.Height
                ZIndex: =3

            StarVisible1 As label:
                Align: =Align.Center
                Height: =DataCardKey1.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey1.Y
                ZIndex: =4

        description_product_DataCard1 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="description_product"
            Default: =ThisItem.description_product
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@product_1],DataSourceInfo.DisplayName,"description_product")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@product_1], DataSourceInfo.MaxLength, "description_product")
            Required: =false
            Update: =DataCardValue2.Text
            Width: =266
            X: =1
            Y: =0
            ZIndex: =6

            DataCardKey2 As label:
                AutoHeight: =true
                Height: =34
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue2 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey2.Y + DataCardKey2.Height + 5
                ZIndex: =2

            ErrorMessage2 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue2.Y + DataCardValue2.Height
                ZIndex: =3

            StarVisible2 As label:
                Align: =Align.Center
                Height: =DataCardKey2.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey2.Y
                ZIndex: =4

        price_product_DataCard1 As typedDataCard.numberEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="price_product"
            Default: =ThisItem.price_product
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@product_1],DataSourceInfo.DisplayName,"price_product")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            Required: =false
            Update: =Value(DataCardValue3.Text)
            Width: =266
            X: =2
            Y: =0
            ZIndex: =6

            DataCardKey3 As label:
                AutoHeight: =true
                Height: =34
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue3 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                Format: =TextFormat.Number
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey3.Y + DataCardKey3.Height + 5
                ZIndex: =2

            ErrorMessage3 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue3.Y + DataCardValue3.Height
                ZIndex: =3

            StarVisible3 As label:
                Align: =Align.Center
                Height: =DataCardKey3.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey3.Y
                ZIndex: =4

    saver_product As button:
        OnSelect: =SubmitForm(Form1)
        Text: ="Save"
        X: =888
        Y: =693
        ZIndex: =6

    cancel As button:
        OnSelect: =Navigate('Main Screen')
        Text: ="Cancel"
        X: =1132
        Y: =693
        ZIndex: =7

